---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "anandyadav7/Hello"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
theme: "Lanyon"
...
