---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://anandyadav7.github.io/Hello"
title: "Hello Welcome"
canonifyurls: True
theme: "Lanyon"
...
